services:
  - type: web
    name: 3d-converter
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main_updated.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
